### ISSUE TITLE
Ingress Controller needs " kubernetes.io/ingress.class:"

### ISSUE THREAD

**Issue by sesispla** [sesispla/generator-kubegen#1]
The current implementation of Ingress Controller do not include a "kubernetes.io/ingress.class" annotation. 

This is causing the Ingress to be deployed to the cluster, but do not expose nothing to the world.

The generated YAML file should look like this:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: nginx
    namespace: default
    annotations:        
        kubernetes.io/ingress.class: "external"
spec:
  rules:
    -   host: mydomain.com
        http:
            paths:
                -
                    path: /
                    backend:
                        serviceName: nginx
                        servicePort: 80
```
