### ISSUE TITLE
Improve yaml-js output format

### ISSUE THREAD

**Issue by sesispla** [sesispla/generator-kubegen#6]
Although yamljs output is valid from a kubectl point of view, the document format might be improved for a better "human reading experience".

e.g. this is an output generated automatically by kubectl, for a ingress with kube-lego:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: nginx
    namespace: default
    annotations:
        kubernetes.io/tls-acme: 'true'
spec:
    rules:
        -
            http:
                paths:
                    -
                        path: /
                        backend:
                            serviceName: nginx
                            servicePort: 80
            host: nginx.minikube.sesispla.net
    tls:
        -
            hosts:
                - nginx.minikube.sesispla.net
            secretName: nginx-secret
```

And how a human might expect the document to be formatted:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: nginx
    namespace: default
    annotations:
        kubernetes.io/tls-acme: 'true'
spec:
    rules:
        - host: nginx.minikube.sesispla.net
            http:
                paths:
                    - path: /
                        backend:
                            serviceName: nginx
                            servicePort: 80
    tls:
        - hosts:
            - nginx.minikube.sesispla.net
            secretName: nginx-secret
```
