### ISSUE TITLE
Allow more Service options

### ISSUE THREAD

**Issue by pulberg** [sesispla/generator-kubegen#7]
It would be nice to allow Services to be external without using an Ingress. k8s Services can be configured as a "LoadBalancer", which then creates an external end-point.  The current service is configured as "ClusterIP"

```yaml
"spec": {
    "ports": [
      {
        "protocol": "TCP",
        "port": 7748,
        "targetPort": 80
      }
    ],
    "selector": {
      "app": "test27"
    },
    "clusterIP": "10.43.33.170",
    "type": "ClusterIP",
    "sessionAffinity": "None"
  }
```

By changing the "type" to "LoadBalancer" you get an external end-point - 

```yaml
"spec": {
    "ports": [
      {
        "protocol": "TCP",
        "port": 7748,
        "targetPort": 80,
        "nodePort": 31813
      }
    ],
    "selector": {
      "app": "test27"
    },
    "clusterIP": "10.43.33.170",
    "type": "LoadBalancer",
    "sessionAffinity": "None",
    "externalTrafficPolicy": "Cluster"
  }
```
